<a href="https://colab.research.google.com/github/soumodeepsen/my-projects/blob/main/fcc_demographic_data_analyzer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment

# Demographic Data Analyzer

In this challenge you must analyze demographic data using Pandas. You are given a dataset of demographic data that was extracted from the 1994 Census database. Here is a sample of what the data looks like:

|    |   age | workclass        |   fnlwgt | education   |   education-num | marital-status     | occupation        | relationship   | race   | sex    |   capital-gain |   capital-loss |   hours-per-week | native-country   | salary   |
|---:|------:|:-----------------|---------:|:------------|----------------:|:-------------------|:------------------|:---------------|:-------|:-------|---------------:|---------------:|-----------------:|:-----------------|:---------|
|  0 |    39 | State-gov        |    77516 | Bachelors   |              13 | Never-married      | Adm-clerical      | Not-in-family  | White  | Male   |           2174 |              0 |               40 | United-States    | <=50K    |
|  1 |    50 | Self-emp-not-inc |    83311 | Bachelors   |              13 | Married-civ-spouse | Exec-managerial   | Husband        | White  | Male   |              0 |              0 |               13 | United-States    | <=50K    |
|  2 |    38 | Private          |   215646 | HS-grad     |               9 | Divorced           | Handlers-cleaners | Not-in-family  | White  | Male   |              0 |              0 |               40 | United-States    | <=50K    |
|  3 |    53 | Private          |   234721 | 11th        |               7 | Married-civ-spouse | Handlers-cleaners | Husband        | Black  | Male   |              0 |              0 |               40 | United-States    | <=50K    |
|  4 |    28 | Private          |   338409 | Bachelors   |              13 | Married-civ-spouse | Prof-specialty    | Wife           | Black  | Female |              0 |              0 |               40 | Cuba             | <=50K    |


You must use Pandas to answer the following questions:
* How many people of each race are represented in this dataset? This should be a Pandas series with race names as the index labels. (`race` column)
* What is the average age of men?
* What is the percentage of people who have a Bachelor's degree?
* What percentage of people with advanced education (`Bachelors`, `Masters`, or `Doctorate`) make more than 50K?
* What percentage of people without advanced education make more than 50K?
* What is the minimum number of hours a person works per week?
* What percentage of the people who work the minimum number of hours per week have a salary of more than 50K?
* What country has the highest percentage of people that earn >50K and what is that percentage?
* Identify the most popular occupation for those who earn >50K in India. 

Use the starter code in the file `demographic_data_analyzer`. Update the code so all variables set to "None" are set to the appropriate calculation or code. Round all decimals to the nearest tenth.

Unit tests are written for you under `test_module.py`.

### Development

For development, you can use `main.py` to test your functions. Click the "run" button and `main.py` will run.

### Testing 

We imported the tests from `test_module.py` to `main.py` for your convenience. The tests will run automatically whenever you hit the "run" button.

### Submitting

Copy your project's URL and submit it to freeCodeCamp.

### Dataset Source

Dua, D. and Graff, C. (2019). UCI Machine Learning Repository [http://archive.ics.uci.edu/ml]. Irvine, CA: University of California, School of Information and Computer Science.

In [ ]:
!wget https://raw.githubusercontent.com/soumodeepsen/datasets/main/adult.data.csv

--2022-07-19 07:59:50--  https://raw.githubusercontent.com/soumodeepsen/my-projects/main/adult.data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3518607 (3.4M) [text/plain]
Saving to: ‘adult.data.csv.1’

adult.data.csv.1    100%[===================>]   3.36M  --.-KB/s    in 0.07s   

2022-07-19 07:59:50 (49.2 MB/s) - ‘adult.data.csv.1’ saved [3518607/3518607]



In [ ]:
from IPython.core.display import clear_output
import pandas as pd

def calculate_demographic_data(print_data=True):
    # Read data from file
    df = pd.read_csv("adult.data.csv")

    # How many of each race are represented in this dataset? This should be a Pandas series with race names as the index labels.
    race_count = pd.Series(df['race']).value_counts()

    # What is the average age of men?
    average_age_men = round(df[df['sex'] == 'Male']['age'].mean(), 1)

    # What is the percentage of people who have a Bachelor's degree?
    percentage_bachelors = round(len(df[df['education']=="Bachelors"])/len(df)*100,1)

    # What percentage of people with advanced education (`Bachelors`, `Masters`, or `Doctorate`) make more than 50K?
    # What percentage of people without advanced education make more than 50K?
  
    # with and without `Bachelors`, `Masters`, or `Doctorate`
    higher_education = df[df['education'].isin(['Bachelors','Masters','Doctorate'])]
    lower_education = df[~df['education'].isin(['Bachelors','Masters','Doctorate'])]

    # percentage with salary >50K
    higher_education_rich =round(len(higher_education[higher_education['salary'] == '>50K'])/len(higher_education)*100,1)
    lower_education_rich =round(len(lower_education[lower_education['salary'] == '>50K'])/len(lower_education)*100,1)

    # What is the minimum number of hours a person works per week (hours-per-week feature)?
    min_work_hours = df['hours-per-week'].min()

    # What percentage of the people who work the minimum number of hours per week have a salary of >50K?
    num_min_workers = df[df['hours-per-week'] == min_work_hours]

    rich_percentage = round(len(num_min_workers[num_min_workers['salary'] == '>50K'])/len(num_min_workers)*100,1)

    # What country has the highest percentage of people that earn >50K?
    highest_earning_list = round(df[df['salary']=='>50K'].value_counts(df['native-country'])/df.value_counts(df['native-country'])*100,1)
    highest_earning_country = highest_earning_list.idxmax()
    highest_earning_country_percentage=round(highest_earning_list.max(),1)

    # Identify the most popular occupation for those who earn >50K in India.
    top_IN_occupation = df.loc[(df['native-country'] == 'India') & (df['salary'] == '>50K')].value_counts(df['occupation']).idxmax()

    # DO NOT MODIFY BELOW THIS LINE

    if print_data:
        print("Number of each race:\n", race_count) 
        print("Average age of men:", average_age_men)
        print(f"Percentage with Bachelors degrees: {percentage_bachelors}%")
        print(f"Percentage with higher education that earn >50K: {higher_education_rich}%")
        print(f"Percentage without higher education that earn >50K: {lower_education_rich}%")
        print(f"Min work time: {min_work_hours} hours/week")
        print(f"Percentage of rich among those who work fewest hours: {rich_percentage}%")
        print("Country with highest percentage of rich:", highest_earning_country)
        print(f"Highest percentage of rich people in country: {highest_earning_country_percentage}%")
        print("Top occupations in India:", top_IN_occupation)

    return {
        'race_count': race_count,
        'average_age_men': average_age_men,
        'percentage_bachelors': percentage_bachelors,
        'higher_education_rich': higher_education_rich,
        'lower_education_rich': lower_education_rich,
        'min_work_hours': min_work_hours,
        'rich_percentage': rich_percentage,
        'highest_earning_country': highest_earning_country,
        'highest_earning_country_percentage':
        highest_earning_country_percentage,
        'top_IN_occupation': top_IN_occupation
    }

clear_output()

In [ ]:
data = calculate_demographic_data()

Number of each race:
 White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: race, dtype: int64
Average age of men: 39.4
Percentage with Bachelors degrees: 16.4%
Percentage with higher education that earn >50K: 46.5%
Percentage without higher education that earn >50K: 17.4%
Min work time: 1 hours/week
Percentage of rich among those who work fewest hours: 10.0%
Country with highest percentage of rich: Iran
Highest percentage of rich people in country: 41.9%
Top occupations in India: Prof-specialty


In [ ]:
calculate_demographic_data(False)

{'average_age_men': 39.4,
 'higher_education_rich': 46.5,
 'highest_earning_country': 'Iran',
 'highest_earning_country_percentage': 41.9,
 'lower_education_rich': 17.4,
 'min_work_hours': 1,
 'percentage_bachelors': 16.4,
 'race_count': White                 27816
 Black                  3124
 Asian-Pac-Islander     1039
 Amer-Indian-Eskimo      311
 Other                   271
 Name: race, dtype: int64,
 'rich_percentage': 10.0,
 'top_IN_occupation': 'Prof-specialty'}

**Expected race count values to be [27816, 3124, 1039, 311, 271]**

In [ ]:
calculate_demographic_data(False)['race_count']

White                 27816
Black                  3124
Asian-Pac-Islander     1039
Amer-Indian-Eskimo      311
Other                   271
Name: race, dtype: int64

**Expected average age of men = 39.4**

In [ ]:
calculate_demographic_data(False)['average_age_men']

39.4

**Expected value for percentage with Bachelors degrees = 16.4**

In [ ]:
calculate_demographic_data(False)['percentage_bachelors']

16.4

**Expected value for percentage with higher education that earn >50K = 46.5**

In [ ]:
calculate_demographic_data(False)['higher_education_rich']

46.5

**Expected value for percentage without higher education that earn >50K = 17.4**

In [ ]:
calculate_demographic_data(False)['lower_education_rich']

17.4

**Expected value for minimum work hours = 1**

In [ ]:
calculate_demographic_data(False)['min_work_hours']

1

**Expected value for percentage of rich among those who work fewest hours = 10**

In [ ]:
calculate_demographic_data(False)['rich_percentage']

10.0

**Expected value for highest earning country = Iran**

In [ ]:
calculate_demographic_data(False)['highest_earning_country']

'Iran'

**Expected value for highest earning country percentage = 41.9**

In [ ]:
calculate_demographic_data(False)['highest_earning_country_percentage']

41.9

**Expected value for top occupations in India = Prof-speciality**

In [ ]:
calculate_demographic_data(False)['top_IN_occupation']

'Prof-specialty'